spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            
      routes:
        - id: login-service
          uri: http://localhost:8081
          predicates:
            - Path=/login/**
          
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/transaction/**
           
        - id: loan-service
          uri: http://localhost:8083
          predicates:
            - Path=/loan/**
           
        - id: locker-service
          uri: http://localhost:8084
          predicates:
            - Path=/locker/**
           
        - id: creditcard-service
          uri: http://localhost:8085
          predicates:
            - Path=/creditcard/**
           
        - id: giftcard-service
          uri: http://localhost:8086
          predicates:
            - Path=/giftcard/**
